{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('check', 'check')", "trace": "self = <sample.test_demo1.TestClass object at 0x000001AFBA165128>\n\n    @pytest.mark.a\n    def test_two(self):\n        x = 'check'\n>       assert hasattr(x,'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('check', 'check')\n\nsample\\test_demo1.py:10: AssertionError"}, "start": 1585459398305, "stop": 1585459398305, "uuid": "f2ce215f-859d-4aea-bc36-929d128458db", "historyId": "a6af45fbd9f81e9bf9120f7c9b50ec47", "testCaseId": "7fa06ebc50830964ee95870a9ffbb1b5", "fullName": "sample.test_demo1.TestClass#test_two", "labels": [{"name": "tag", "value": "a"}, {"name": "parentSuite", "value": "sample"}, {"name": "suite", "value": "test_demo1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "DESKTOP-3BKS4R6"}, {"name": "thread", "value": "9828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "sample.test_demo1"}]}