{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\ntestcases\\test_inc.py:5: AssertionError"}, "start": 1585459398415, "stop": 1585459398415, "uuid": "3934d69f-1169-436c-870b-3b7b70083c2f", "historyId": "009eb7e016b5546642a9f80ac231fbe7", "testCaseId": "8a8207b8c71415199ce71304892d8ebe", "fullName": "testcases.test_inc#test_answer", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_inc"}, {"name": "host", "value": "DESKTOP-3BKS4R6"}, {"name": "thread", "value": "9828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_inc"}]}